valueb = ord('b')
valuec = ord('C')
valued = ord('D')
valuebb = ord('b')
valuecc = ord('c')
valuedd = ord('d')
valuezero = ord('0')
valueone = ord('1')
valuetwo = ord('2')
valuedollar = ord('$')
valuestar = ord('*')
valueplus = ord('+')
valuespace = ord(' ')
print(valueb, valuec, valued, valuebb, valuecc, valuedd, valuezero, valueone, valuetwo, valuedollar, valuestar, valueplus, valuespace)